Traceback (most recent call last):
  File "C:\Users\gabyd\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\gabyd\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabyd\AppData\Roaming\Python\Python312\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabyd\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\gabyd\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\gabyd\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\gabyd\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
alt.Chart(zipcodes).mark_square(
    size=1, opacity=1
).encode( 
    longitude='longitude:Q', # aplica o campo chamado 'longitude' para o canal "longitude".
    latitude='latitude:Q'    # aplica o campo chamado 'latitude' para o canal "latitude".
    type='albersUsa'
).properties(
    width=900,
    height=500
).configure_view(
    stroke=None
)
------------------


[1;36m  Cell [1;32mIn[15], line 5[1;36m[0m
[1;33m    latitude='latitude:Q'    # aplica o campo chamado 'latitude' para o canal "latitude".[0m
[1;37m             ^[0m
[1;31mSyntaxError[0m[1;31m:[0m invalid syntax. Perhaps you forgot a comma?


